name: Laravel CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    tests:
        runs-on: ubuntu-latest

        env:
            DB_USERNAME: sail
            DB_DATABASE: valorantskilllab
            DB_PASSWORD: password
            DB_HOST: pgsql
            DB_PORT: 5432
            DB_CONNECTION: pgsql

        steps:
            - uses: actions/checkout@v3

            - name: cp env
              run: cp .env.example .env

            - name: composer install
              run: docker run --rm -u "$(id -u):$(id -g)" -v $(pwd):/var/www/html -w /var/www/html laravelsail/php81-composer:latest composer install --ignore-platform-reqs

            # 先に起動しておく
            - name: start　postgres
              run: ./vendor/bin/sail up -d postgres

            - name: start
              run: ./vendor/bin/sail up -d

            - name: generate key
              run: ./vendor/bin/sail artisan key:generate

            - name: migrate
              run: ./vendor/bin/sail artisan migrate

            - name: test
              run: ./vendor/bin/sail test
