name: Laravel CI without Sail

on: [push, pull_request]

jobs:
    laravel:
        name: Laravel (PHP ${{ matrix.php-versions }})
        runs-on: ubuntu-latest
        environment: GitHub Actions
        env:
            DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_DATABASE: ${{ secrets.DB_DATABASE }}
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_USER: ${{ secrets.DB_USERNAME }}
                    POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
                    POSTGRES_DB: ${{ secrets.DB_DATABASE }}
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

        strategy:
            fail-fast: false
            matrix:
                php-versions: ['8.1']

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, dom, fileinfo, pgsql
                  coverage: none

            # envファイルがなければ.env.exampleをコピーする
            - name: Copy .env
              run: php -r "file_exists('.env') || copy('.env.example', '.env');"

            # Composerのキャッシュをインストール
            - name: Install Composer dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            # Node.jsのセットアップ
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            # Node.jsの依存関係をインストール
            - name: Install Node.js dependencies
              run: npm ci

            # Viteのアセットをビルド
            - name: Build Vite assets
              run: npm run build

            # vitestのテストを実行
            - name: Run vitest tests
              env:
                  LARAVEL_BYPASS_ENV_CHECK: ${{ secrets.LARAVEL_BYPASS_ENV_CHECK }}
              run: npx vitest

            # キーの生成
            - name: Prepare the application
              run: |
                  php artisan key:generate

            # マイグレーションの実行
            - name: Run Migration
              run: php artisan migrate -v

            # テストの実行
            - name: Run Phpunit
              run: vendor/bin/phpunit
